"""Initial migration

Revision ID: 2ba8c4c5e989
Revises: 
Create Date: 2024-11-04 02:04:08.111694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba8c4c5e989'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oficina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('professor', sa.String(length=100), nullable=False),
    sa.Column('horario', sa.String(length=50), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('vagas_total', sa.Integer(), nullable=False),
    sa.Column('vagas_disponiveis', sa.Integer(), nullable=False),
    sa.Column('imagem', sa.String(length=200), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('oficina_id', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['oficina_id'], ['oficina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inscricao')
    op.drop_table('oficina')
    # ### end Alembic commands ###
